export const cardData = {
  data: [
    {
      id: 1,
      name: "Vanilla IceCream",
      weight: "200gm",
      type: "bar",
      color: "#F3E5AB",
      price: 20,
      qty: 0,
    },
    {
      id: 2,
      name: "Chocolate IceCream",
      weight: "200gm",
      type: "bar",
      color: "#7B3F00",
      price: 20,
      qty: 0,
    },
    {
      id: 3,
      name: "Butterscotch IceCream",
      weight: "200gm",
      type: "bar",
      color: "#E3963E",
      price: 20,
      qty: 0,
    },
    {
      id: 4,
      name: "Strawberry IceCream",
      weight: "200gm",
      type: "bar",
      color: "#fc5a8d",
      price: 20,
      qty: 0,
    },
  ],
};
